services:
  prediction-engine-tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - TEST_DB_ADMIN_URL=postgresql://postgres:password@db:5432/postgres
      - TEST_DB_URL=postgresql://postgres:password@db:5432/test_intellacc
    depends_on:
      - db
    command: >-
      bash -c "export PATH=/usr/local/cargo/bin:$PATH; export PGPASSWORD=password; until pg_isready -h db -U postgres; do sleep 1; done; if [ \"$(psql -h db -U postgres -d postgres -tAc \"SELECT 1 FROM pg_database WHERE datname='test_intellacc'\")\" != \"1\" ]; then psql -h db -U postgres -d postgres -c \"CREATE DATABASE test_intellacc\"; fi; cargo test -- --nocapture"

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_intellacc
    volumes:
      - prediction_engine_test_db:/var/lib/postgresql/data

volumes:
  prediction_engine_test_db:
